#http://localhost:8080/h2-console/login.jsp?jsessionid=9e3523cbded72771c9dd2627ebd87e9b

spring:
  datasource:
    url: jdbc:h2:mem:datingapp
    username: admin
    password: password
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html